T5247: Bug command "show interfaces system"
vyos-legacy/vyatta-op pull request #63
Opened 2023-06-09 08:01 UTC by cuongdt1994

Fixed bug command show more RX and TX with "show interfaces system"

![image](https://github.com/vyos/vyatta-op/assets/63875204/9c9f0d37-c8c8-4db0-a858-57f0e0d0210e)

2023-06-09 16:40 UTC, cuongdt1994 commented
This command displays the network cards present in the system, can now be replaced with this command

command: show interfaces detail

Function the same.

Example:

With command show interfaces detail

![image](https://github.com/vyos/vyatta-op/assets/63875204/1ee15915-bfb1-471a-8f23-222fa8bf936b)

and with command show interfaces system

![image](https://github.com/vyos/vyatta-op/assets/63875204/4404c942-1cc9-46e2-8eab-6d856cdf7e44)

2023-06-09 20:15 UTC, cuongdt1994 commented
Currently I have 1 question, is this VRRP function still working?

help: Show vrrp interface information
run: ${vyatta_bindir}/vyatta-show-interfaces.pl --vrrp --action=show-brief

If it still works, I will edit it again.

2023-08-11 08:14 UTC, sever-sever approved these changes

2023-08-11 08:27 UTC, dmbaturin requested changes
Why even bother fixing a Perl script when a Python version of `show interfaces` has existed for years? We are _removing_ Perl code, not extending it.

Also, the commit history in this PR really confuses me. Why does it seem to re-add the vyatta-show-interfaces.pl script and its Makefile.am entries? The diff must reflect the fix. If it's like a simple fix to the script, please make the commit reflect the fix.

2023-12-09 15:36 UTC, closed without merging